'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Vendedor
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''txtMensagemVendedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMensagemVendedor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNomeVendedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeVendedor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rdbMasculino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbMasculino As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rdbFeminino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbFeminino As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txtSalario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalario As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDataAdmissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataAdmissao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDataDemissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataDemissao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnNovoVendedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNovoVendedor As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnEditarVendedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditarVendedor As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnExcluirVendedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExcluirVendedor As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSalvarVendedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvarVendedor As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelarVend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelarVend As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtPesquisarVendedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPesquisarVendedor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnPesquisarVendedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPesquisarVendedor As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''grdVendedores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdVendedores As Global.System.Web.UI.WebControls.GridView
End Class
